"""Add last_synced_at to Playlist model

Revision ID: 3e94dca99d0d
Revises: b4abab401265
Create Date: 2026-01-07 02:21:37.485040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3e94dca99d0d"
down_revision: Union[str, Sequence[str], None] = "b4abab401265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playlist",
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlist", "last_synced_at")
    # ### end Alembic commands ###
